name: chart test
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'
      - run: |
          kubectl get pods -A
          sleep 20
          kubectl get pods -A
